services:
  - type: web
    name: heart-disease-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "pip install uvicorn fastapi && python -m uvicorn api.app:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0